// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// count_fastq_barcodes_cpp
Rcpp::List count_fastq_barcodes_cpp(Rcpp::CharacterVector fq, Rcpp::CharacterVector sample_barcodes, Rcpp::CharacterVector construct_barcodes, Rcpp::IntegerVector sample_start, Rcpp::IntegerVector sample_width, Rcpp::IntegerVector construct_start, Rcpp::IntegerVector construct_width, bool verbose);
RcppExport SEXP _pepitope_count_fastq_barcodes_cpp(SEXP fqSEXP, SEXP sample_barcodesSEXP, SEXP construct_barcodesSEXP, SEXP sample_startSEXP, SEXP sample_widthSEXP, SEXP construct_startSEXP, SEXP construct_widthSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type fq(fqSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sample_barcodes(sample_barcodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type construct_barcodes(construct_barcodesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_start(sample_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sample_width(sample_widthSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type construct_start(construct_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type construct_width(construct_widthSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(count_fastq_barcodes_cpp(fq, sample_barcodes, construct_barcodes, sample_start, sample_width, construct_start, construct_width, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pepitope_count_fastq_barcodes_cpp", (DL_FUNC) &_pepitope_count_fastq_barcodes_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_pepitope(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
