# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_fastq_barcodes_cpp <- function(fq, sample_barcodes, construct_barcodes, sample_start, sample_width, construct_start, construct_width, verbose) {
    .Call(`_pepitope_count_fastq_barcodes_cpp`, fq, sample_barcodes, construct_barcodes, sample_start, sample_width, construct_start, construct_width, verbose)
}

